#!/bin/bash

alias ..='cd ..'
alias ...='cd ../..'
alias lr='find .'

alias gs='git status'
alias gd='git diff --cached'
alias gitroot='cd $(git rev-parse --show-toplevel)'

alias lsdrives='lslblk'
alias gpg='gpg2'
alias sagi='sudo apt-get install'
alias ebash='vim ~/.bash; source ~/.bashrc'
